In [1]:
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import train_test_split

import numpy as np
import pandas as pd
import tensorflow as tf

Using TensorFlow backend.


In [2]:
# seed 값 설정
seed = 0
np.random.seed(seed)
tf.set_random_seed(seed)

In [3]:
df = pd.read_csv('./input/train.csv')
df.tail(5)

id             date      price  bedrooms  bathrooms  sqft_living  \
15030  15030  20141014T000000   610685.0         4       2.50         2520   
15031  15031  20150326T000000  1007500.0         4       3.50         3510   
15032  15032  20140521T000000   360000.0         3       2.50         1530   
15033  15033  20150223T000000   400000.0         4       2.50         2310   
15034  15034  20141015T000000   325000.0         2       0.75         1020   

       sqft_lot  floors  waterfront  view  ...  grade  sqft_above  \
15030      6023     2.0           0     0  ...      9        2520   
15031      7200     2.0           0     0  ...      9        2600   
15032      1131     3.0           0     0  ...      8        1530   
15033      5813     2.0           0     0  ...      8        2310   
15034      1076     2.0           0     0  ...      7        1020   

       sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
15030              0      2014             0    98056  47.5137 -122.167   
15031            910      2009             0    98136  47.5537 -122.398   
15032              0      2009             0    98103  47.6993 -122.346   
15033              0      2014             0    98146  47.5107 -122.362   
15034              0      2008             0    98144  47.5941 -122.299   

       sqft_living15  sqft_lot15  
15030           2520        6023  
15031           2050        6200  
15032           1530        1509  
15033           1830        7200  
15034           1020        1357  

[5 rows x 21 columns]

In [4]:
dataset = df.values
# id, date ,price 빼고 저장
X = dataset[:,3:21]
# price만 담음
Y = dataset[:,2]
X[0]

array([3, 1.0, 1180, 5650, 1.0, 0, 0, 3, 7, 1180, 0, 1955, 0, 98178,
       47.5112, -122.257, 1340, 5650], dtype=object)

In [5]:
Y

array([221900.0, 180000.0, 510000.0, ..., 360000.0, 400000.0, 325000.0],
      dtype=object)

In [6]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.001, random_state=seed)

In [7]:
model = Sequential()
model.add(Dense(30, input_dim=18, activation='relu'))
model.add(Dense(6, activation='relu'))
model.add(Dense(3, activation='relu'))
model.add(Dense(1))

Instructions for updating:
Colocations handled automatically by placer.


In [8]:
model.compile(loss='mean_squared_error',
             optimizer='adam')

In [9]:
model.fit(X_train, Y_train, epochs=300, batch_size=500)

Instructions for updating:
Use tf.cast instead.
Epoch 1/300
15019/15019 [==============================] - 2s 141us/step - loss: 426229197880.1124
Epoch 2/300
15019/15019 [==============================] - 0s 14us/step - loss: 416608338955.2498
Epoch 3/300
15019/15019 [==============================] - 0s 15us/step - loss: 392216599615.4759
Epoch 4/300
15019/15019 [==============================] - 0s 16us/step - loss: 354317691565.2120
Epoch 5/300
15019/15019 [==============================] - 0s 16us/step - loss: 300905962006.3973
Epoch 6/300
15019/15019 [==============================] - 0s 14us/step - loss: 234845201484.1574
Epoch 7/300
15019/15019 [==============================] - 0s 12us/step - loss: 180658668095.9872
Epoch 8/300
15019/15019 [==============================] - 0s 12us/step - loss: 153622669128.5950
Epoch 9/300
15019/15019 [==============================] - 0s 13us/step - loss: 140904931553.2677
Epoch 10/300
15019/15019 [==============================] - 0s 17us/s

15019/15019 [==============================] - 0s 15us/step - loss: 58177275764.7758
Epoch 82/300
15019/15019 [==============================] - 0s 17us/step - loss: 58097144683.9806
Epoch 83/300
15019/15019 [==============================] - 0s 17us/step - loss: 58058657081.2885
Epoch 84/300
15019/15019 [==============================] - 0s 17us/step - loss: 58104524156.6506
Epoch 85/300
15019/15019 [==============================] - 0s 17us/step - loss: 57918923125.6281
Epoch 86/300
15019/15019 [==============================] - 0s 15us/step - loss: 57867129114.2665
Epoch 87/300
15019/15019 [==============================] - 0s 15us/step - loss: 57777658666.1184
Epoch 88/300
15019/15019 [==============================] - 0s 17us/step - loss: 57832612310.7168
Epoch 89/300
15019/15019 [==============================] - 0s 16us/step - loss: 57736819604.2069
Epoch 90/300
15019/15019 [==============================] - 0s 14us/step - loss: 57634697934.7568
Epoch 91/300
15019/15019 [=======

15019/15019 [==============================] - 0s 14us/step - loss: 55848660127.6101
Epoch 164/300
15019/15019 [==============================] - 0s 16us/step - loss: 55485193609.4685
Epoch 165/300
15019/15019 [==============================] - 0s 17us/step - loss: 55511808469.6259
Epoch 166/300
15019/15019 [==============================] - 0s 16us/step - loss: 55529352727.0109
Epoch 167/300
15019/15019 [==============================] - 0s 14us/step - loss: 55523222727.9728
Epoch 168/300
15019/15019 [==============================] - 0s 13us/step - loss: 55612063982.3583
Epoch 169/300
15019/15019 [==============================] - 0s 14us/step - loss: 55518518543.6985
Epoch 170/300
15019/15019 [==============================] - 0s 17us/step - loss: 55460604978.3852
Epoch 171/300
15019/15019 [==============================] - 0s 17us/step - loss: 55434863679.0668
Epoch 172/300
15019/15019 [==============================] - 0s 17us/step - loss: 55460822602.5552
Epoch 173/300
15019/1501

15019/15019 [==============================] - 0s 15us/step - loss: 54693945864.8975
Epoch 246/300
15019/15019 [==============================] - 0s 16us/step - loss: 54800825907.3739
Epoch 247/300
15019/15019 [==============================] - 0s 17us/step - loss: 54665734442.2207
Epoch 248/300
15019/15019 [==============================] - 0s 16us/step - loss: 54680408785.6203
Epoch 249/300
15019/15019 [==============================] - 0s 16us/step - loss: 54705407808.9588
Epoch 250/300
15019/15019 [==============================] - 0s 16us/step - loss: 54611001814.1714
Epoch 251/300
15019/15019 [==============================] - 0s 17us/step - loss: 54582967743.7401
Epoch 252/300
15019/15019 [==============================] - 0s 17us/step - loss: 54954227804.3161: 0s - loss: 55264330100.36
Epoch 253/300
15019/15019 [==============================] - 0s 16us/step - loss: 54675352307.0287
Epoch 254/300
15019/15019 [==============================] - 0s 17us/step - loss: 54563711253.90

## batch size
* 배치사이즈는 몇 문항을 풀고 해답을 맞추는 지를 의미합니다. 100문항일 때, 배치사이즈가 100이면 전체를 다 풀고 난 뒤에 해답을 맞춰보는 것입니다. 
* 배치사이즈가 10이면 열 문제씩 풀어보고 해답 맞춰보는 것입니다. 100문항을 10문제씩 나누어서 10번 해답을 맞추므로 가중치 갱신은 10번 일어납니다.
* 배치사이즈가 작을수록 가중치 갱신이 자주 일어납니다.

## epochs
* 에포크는 모의고사 1회분을 몇 번 풀어볼까 입니다. 즉 100문항의 문제들을 몇 번이나 반복해서 풀어보는 지 정하는 것입니다. 에포크가 20이면 모의고사 1회분을 20번 푸는 것입니다. 처음에는 같은 문제를 반복적으로 풀어보는 것이 무슨 효과가 있는 지 의문이 들었지만 우리가 같은 문제집을 여러 번 풀면서 점차 학습되듯이 모델도 같은 데이터셋으로 반복적으로 가중치를 갱신하면서 모델이 학습됩니다. 같은 문제라도 이전에 풀었을 때랑 지금 풀었을 때랑 학습상태(가중치)가 다르기 때문에 다시 학습이 일어납니다.
* 같은 문제집이라도 반복해서 풀면 학습이 일어납니다.
* 모의고사 1회분을 20번 푸는 것과 서로 다른 모의고사 20회분을 1번 푸는 것과는 어떤 차이가 있을까요? 이것은 분야에 따라 데이터특성에 따라 다를 것이라고 생각합니다. 잡다한 문제를 많이 푸는 것보다 양질의 문제를 여러 번 푸는 것이 도움이 된다고 생각합니다. 피아노를 배울 때도 기본 곡을 반복적으로 학습하면 다양한 악보도 쉽게 보는 반면 이곡 저곡 연습하면 제대로 익히기 쉽지 않습니다. 이런 문제를 제외하고도 현실적으로 데이터를 구하기가 쉽지 않기 때문에 제한된 데이터셋으로 반복적으로 학습하는 것이 효율적입니다.

In [30]:
# 7:3으로 쪼갬 (30,6,1)
# 예측 값과 실제 값의 비교 - epoch = 10의 결과
Y_prediction = model.predict(X_test).flatten()
for i in range(10):
    label = Y_test[i]
    prediction = Y_prediction[i]
    print("실제가격: {:.3f}, 예상가격: {:.3f}".format(label, prediction))

실제가격: 380000.000, 예상가격: 188821.375
실제가격: 950000.000, 예상가격: 1198259.875
실제가격: 580000.000, 예상가격: 637780.312
실제가격: 335000.000, 예상가격: 194153.109
실제가격: 861990.000, 예상가격: 1022958.688
실제가격: 410000.000, 예상가격: 317610.125
실제가격: 342400.000, 예상가격: 382523.750
실제가격: 748000.000, 예상가격: 830348.312
실제가격: 492000.000, 예상가격: 696375.188
실제가격: 1142000.000, 예상가격: 766436.938


In [32]:
# 7:3으로 쪼갬 (30,6,1)
# 예측 값과 실제 값의 비교 - epoch = 200의 결과 - los 50
Y_prediction = model.predict(X_test).flatten()
for i in range(10):
    label = Y_test[i]
    prediction = Y_prediction[i]
    print("실제가격: {:.3f}, 예상가격: {:.3f}".format(label, prediction))

실제가격: 380000.000, 예상가격: 309096.719
실제가격: 950000.000, 예상가격: 1269885.750
실제가격: 580000.000, 예상가격: 654275.875
실제가격: 335000.000, 예상가격: 251189.109
실제가격: 861990.000, 예상가격: 1001344.938
실제가격: 410000.000, 예상가격: 329298.625
실제가격: 342400.000, 예상가격: 390568.469
실제가격: 748000.000, 예상가격: 784984.062
실제가격: 492000.000, 예상가격: 669180.625
실제가격: 1142000.000, 예상가격: 723493.375


In [13]:
# 9:1로 쪼갬 (30,6,1)
# 예측 값과 실제 값의 비교 - epoch = 300의 결과 - loss 46
Y_prediction = model.predict(X_test).flatten()
for i in range(30):
    label = Y_test[i]
    prediction = Y_prediction[i]
    print("실제가격: {:.3f}, 예상가격: {:.3f},      오차: {:.3f}".format(label, prediction, abs(label - prediction)))

실제가격: 380000.000, 예상가격: 300420.375,      오차: 79579.625
실제가격: 950000.000, 예상가격: 981992.000,      오차: 31992.000
실제가격: 580000.000, 예상가격: 637040.688,      오차: 57040.688
실제가격: 335000.000, 예상가격: 230373.797,      오차: 104626.203
실제가격: 861990.000, 예상가격: 764127.188,      오차: 97862.812
실제가격: 410000.000, 예상가격: 324789.031,      오차: 85210.969
실제가격: 342400.000, 예상가격: 423471.406,      오차: 81071.406
실제가격: 748000.000, 예상가격: 715748.625,      오차: 32251.375
실제가격: 492000.000, 예상가격: 685383.500,      오차: 193383.500
실제가격: 1142000.000, 예상가격: 762045.812,      오차: 379954.188
실제가격: 345000.000, 예상가격: 500264.719,      오차: 155264.719
실제가격: 292000.000, 예상가격: 450863.469,      오차: 158863.469
실제가격: 286000.000, 예상가격: 445862.375,      오차: 159862.375
실제가격: 705000.000, 예상가격: 473212.250,      오차: 231787.750
실제가격: 210000.000, 예상가격: 325764.844,      오차: 115764.844
실제가격: 329950.000, 예상가격: 323600.281,      오차: 6349.719
실제가격: 436800.000, 예상가격: 458993.938,      오차: 22193.938
실제가격: 543000.000, 예상가격: 477974.594,      오차: 65025.406
실제

In [19]:
# 99:1로 쪼갬
# 층을 하나 늘림, dense=3을 추가 (30,6,3,1)
# batch size 10에서 128로 늘림
# 예측 값과 실제 값의 비교 - epoch = 300의 결과 / epoch당 순회 속도가 7초에서 1초로 줄어듬 - loss 53
Y_prediction = model.predict(X_test).flatten()
for i in range(10):
    label = Y_test[i]
    prediction = Y_prediction[i]
    print("실제가격: {:.3f}, 예상가격: {:.3f},      오차: {:.3f}".format(label, prediction, abs(label - prediction)))

실제가격: 380000.000, 예상가격: 332577.062,      오차: 47422.938
실제가격: 950000.000, 예상가격: 1279008.000,      오차: 329008.000
실제가격: 580000.000, 예상가격: 694180.188,      오차: 114180.188
실제가격: 335000.000, 예상가격: 225536.703,      오차: 109463.297
실제가격: 861990.000, 예상가격: 982693.188,      오차: 120703.188
실제가격: 410000.000, 예상가격: 326779.062,      오차: 83220.938
실제가격: 342400.000, 예상가격: 410596.188,      오차: 68196.188
실제가격: 748000.000, 예상가격: 796374.938,      오차: 48374.938
실제가격: 492000.000, 예상가격: 709275.312,      오차: 217275.312
실제가격: 1142000.000, 예상가격: 757918.312,      오차: 384081.688


In [10]:
# restart kernel
# 99:1로 쪼갬
# 층을 하나 늘림, dense=3을 추가 (30,6,3,1)
# batch size 다시 10으로 줄임
# 예측 값과 실제 값의 비교 - epoch = 300의 결과 / epoch당 순회 속도 9초 - loss 46
Y_prediction = model.predict(X_test).flatten()
for i in range(10):
    label = Y_test[i]
    prediction = Y_prediction[i]
    print("실제가격: {:.3f}, 예상가격: {:.3f},      오차: {:.3f}".format(label, prediction, abs(label - prediction)))

실제가격: 380000.000, 예상가격: 297041.000,      오차: 82959.000
실제가격: 950000.000, 예상가격: 979617.688,      오차: 29617.688
실제가격: 580000.000, 예상가격: 630454.000,      오차: 50454.000
실제가격: 335000.000, 예상가격: 269082.875,      오차: 65917.125
실제가격: 861990.000, 예상가격: 812836.000,      오차: 49154.000
실제가격: 410000.000, 예상가격: 325695.938,      오차: 84304.062
실제가격: 342400.000, 예상가격: 475397.000,      오차: 132997.000
실제가격: 748000.000, 예상가격: 747869.312,      오차: 130.688
실제가격: 492000.000, 예상가격: 657918.688,      오차: 165918.688
실제가격: 1142000.000, 예상가격: 735634.062,      오차: 406365.938


In [20]:
# restart kernel
# 999:1로 쪼갬
# 층을 하나 늘림, dense=3을 추가 (30,6,3,1)b
# batch size 500으로 함                                                             
# 예측 값과 실제 값의 비교 - epoch = 300의 결과 / epoch당 순회 속도 0.몇초 - loss 54
Y_prediction = model.predict(X_test).flatten()
for i in range(10):
    label = Y_test[i]
    prediction = Y_prediction[i]
    print("실제가격: {:.3f}, 예상가격: {:.3f},      오차: {:.3f}".format(label, prediction, abs(label - prediction)))

실제가격: 380000.000, 예상가격: 326839.281,      오차: 53160.719
실제가격: 950000.000, 예상가격: 1292310.875,      오차: 342310.875
실제가격: 580000.000, 예상가격: 631366.188,      오차: 51366.188
실제가격: 335000.000, 예상가격: 285191.531,      오차: 49808.469
실제가격: 861990.000, 예상가격: 1016752.938,      오차: 154762.938
실제가격: 410000.000, 예상가격: 362667.250,      오차: 47332.750
실제가격: 342400.000, 예상가격: 396665.594,      오차: 54265.594
실제가격: 748000.000, 예상가격: 810334.875,      오차: 62334.875
실제가격: 492000.000, 예상가격: 676711.375,      오차: 184711.375
실제가격: 1142000.000, 예상가격: 733225.625,      오차: 408774.375


In [19]:
print(X_train[0])
print(len(X_train))

[3 1.75 2080 12714 2.0 0 0 4 8 1540 540 1984 0 98052 47.7056 -122.162 2080
 12107]
15019


In [13]:
print(X_test[0])

[2 1.0 1000 4800 1.0 0 0 3 6 1000 0 1952 0 98117 47.6926 -122.362 1000
 4800]


In [14]:
print(Y_train[0])

436800.0


In [17]:
print(len(Y_test))

16


In [24]:
#실제 Y 예측하기
test = pd.read_csv('./input/test.csv')
# real_prediction = model.predict(test) 이렇게 집어 넣으면, 입력 커럼수가 달라서 안 됨
data = test.values
X_test = data[:, 2:21]
real_prediction = model.predict(X_test)
print(real_prediction)

[[ 767016.  ]
 [ 491297.22]
 [1287809.2 ]
 ...
 [ 436199.12]
 [ 367684.4 ]
 [ 477480.  ]]


In [25]:
hi = pd.read_csv('./sample_submission.csv')
hi.head(5)

id   price
0  15035  100000
1  15036  100000
2  15037  100000
3  15038  100000
4  15039  100000

In [38]:
new = hi.values

In [46]:
# pred_value = real_prediction.values
print(type(real_prediction))
print(real_prediction.shape)

<class 'numpy.ndarray'>
(6468, 1)


In [49]:
print(type(new))
print(new.shape)

<class 'numpy.ndarray'>
(6468, 2)


In [63]:
new[:,1]

array([100000, 100000, 100000, ..., 100000, 100000, 100000], dtype=int64)

In [68]:
hello = real_prediction.flatten() # new는 1행에 다 담겨있었고, real prediction은 6000행 1열이었음

In [69]:
hello

array([ 767016.  ,  491297.22, 1287809.2 , ...,  436199.12,  367684.4 ,
        477480.  ], dtype=float32)

In [70]:
new[:,1] = hello

In [77]:
print(new)
print(type(new))

[[  15035  767016]
 [  15036  491297]
 [  15037 1287809]
 ...
 [  21500  436199]
 [  21501  367684]
 [  21502  477480]]
<class 'numpy.ndarray'>


In [75]:
np.savetxt("submission.csv", new, delimiter=",")

In [79]:
pd.DataFrame(new).to_csv("submission2.csv")

In [80]:
a = pd.read_csv("submission2.csv")
a

Unnamed: 0      0        1
0              0  15035   767016
1              1  15036   491297
2              2  15037  1287809
3              3  15038   432146
4              4  15039   475544
5              5  15040   541200
6              6  15041   408966
7              7  15042   628200
8              8  15043   409014
9              9  15044   412020
10            10  15045   637401
11            11  15046   328733
12            12  15047   847180
13            13  15048   345840
14            14  15049   646587
15            15  15050   302046
16            16  15051   747577
17            17  15052   449395
18            18  15053   702842
19            19  15054   434688
20            20  15055   590485
21            21  15056   668722
22            22  15057   959736
23            23  15058   614274
24            24  15059   433028
25            25  15060   322879
26            26  15061   492014
27            27  15062   627966
28            28  15063   514681
29            29  15064   429250
...          ...    ...      ...
6438        6438  21473   469421
6439        6439  21474  1083092
6440        6440  21475  1527163
6441        6441  21476   393345
6442        6442  21477   994462
6443        6443  21478   442500
6444        6444  21479  1361480
6445        6445  21480  1727679
6446        6446  21481   506319
6447        6447  21482   512604
6448        6448  21483   598098
6449        6449  21484   785467
6450        6450  21485   435299
6451        6451  21486   467204
6452        6452  21487   598071
6453        6453  21488   499819
6454        6454  21489   370228
6455        6455  21490   394984
6456        6456  21491  1669943
6457        6457  21492   705595
6458        6458  21493   433907
6459        6459  21494   638463
6460        6460  21495   401720
6461        6461  21496   490327
6462        6462  21497   772120
6463        6463  21498   319381
6464        6464  21499   470763
6465        6465  21500   436199
6466        6466  21501   367684
6467        6467  21502   477480

[6468 rows x 3 columns]